version: "3.8"
services:
  main-app:
    build: .
    ports:
      - "8080:8080"
    command: bash -c 'request-limit'
    depends_on:
      - "redis"
    links:
      - "redis"
    volumes:
      - ".:/go/src/github.com/request-limit"
    environment: 
      - REDIS_ADDRESS=redis:6379
      - GIN_MODE=release
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
