version: "3.8"
services:
  main-app:
    build: .
    ports:
      - "8000:8000"
    command: request-limit
    links:
      - "redis"
    volumes:
      - ".:/go/src/github.com/request-limit"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
